language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
  - jruby-9.0.5.0
  - jruby-9.1.9.0
  - jruby-head
gemfile:
  - gemfiles/Gemfile-5-0-stable
  - gemfiles/Gemfile-5-1-stable
  - gemfiles/Gemfile-6-0-stable
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email: false
