language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - 2.5.7
  - 2.6.5
  - ruby-head
  - jruby-9.0.5.0
  - jruby-9.1.9.0
  - jruby-head
gemfile:
  - gemfiles/Gemfile-4-0-stable
  - gemfiles/Gemfile-4-1-stable
  - gemfiles/Gemfile-4-2-stable
  - gemfiles/Gemfile-5-0-stable
  - gemfiles/Gemfile-5-1-stable
  - gemfiles/Gemfile-6-0-stable
matrix:
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-4-0-stable
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-4-1-stable
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-4-0-stable
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-4-1-stable
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email: false
