language: ruby
rvm:
  - 2.4.9
  - 2.5.8
  - 2.6.6
  - 2.7.2
gemfile:
  - gemfiles/Gemfile-4-2-stable
  - gemfiles/Gemfile-5-0-stable
  - gemfiles/Gemfile-5-1-stable
  - gemfiles/Gemfile-6-0-stable
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
notifications:
  email: false
