language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - jruby-9.1.17.0
  - jruby-9.2.14.0
gemfile:
  - gemfiles/Gemfile-5-0-stable
  - gemfiles/Gemfile-5-1-stable
  - gemfiles/Gemfile-5-2-stable
  - gemfiles/Gemfile-6-0-stable
matrix:
  exclude:
    - rvm: jruby-9.1.17.0
      gemfile: gemfiles/Gemfile-6-0-stable
  allow_failures:
    - rvm: 2.7.2
    - rvm: 3.0.0
    - rvm: ruby-head
    - rvm: jruby-9.2.14.0
    - rvm: jruby-head
notifications:
  email: false
